// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculate.proto

#ifndef PROTOBUF_calculate_2eproto__INCLUDED
#define PROTOBUF_calculate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_calculate_2eproto();
void protobuf_InitDefaults_calculate_2eproto();
void protobuf_AssignDesc_calculate_2eproto();
void protobuf_ShutdownFile_calculate_2eproto();

class CalcRequest;
class CalcResponse;

// ===================================================================

class CalcRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CalcRequest) */ {
 public:
  CalcRequest();
  virtual ~CalcRequest();

  CalcRequest(const CalcRequest& from);

  inline CalcRequest& operator=(const CalcRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalcRequest& default_instance();

  static const CalcRequest* internal_default_instance();

  void Swap(CalcRequest* other);

  // implements Message ----------------------------------------------

  inline CalcRequest* New() const { return New(NULL); }

  CalcRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalcRequest& from);
  void MergeFrom(const CalcRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CalcRequest* other);
  void UnsafeMergeFrom(const CalcRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 a = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // optional int32 b = 2;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CalcRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_calculate_2eproto_impl();
  friend void  protobuf_AddDesc_calculate_2eproto_impl();
  friend void protobuf_AssignDesc_calculate_2eproto();
  friend void protobuf_ShutdownFile_calculate_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CalcRequest> CalcRequest_default_instance_;

// -------------------------------------------------------------------

class CalcResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CalcResponse) */ {
 public:
  CalcResponse();
  virtual ~CalcResponse();

  CalcResponse(const CalcResponse& from);

  inline CalcResponse& operator=(const CalcResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalcResponse& default_instance();

  static const CalcResponse* internal_default_instance();

  void Swap(CalcResponse* other);

  // implements Message ----------------------------------------------

  inline CalcResponse* New() const { return New(NULL); }

  CalcResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalcResponse& from);
  void MergeFrom(const CalcResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CalcResponse* other);
  void UnsafeMergeFrom(const CalcResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CalcResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_calculate_2eproto_impl();
  friend void  protobuf_AddDesc_calculate_2eproto_impl();
  friend void protobuf_AssignDesc_calculate_2eproto();
  friend void protobuf_ShutdownFile_calculate_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CalcResponse> CalcResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CalcRequest

// optional int32 a = 1;
inline void CalcRequest::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 CalcRequest::a() const {
  // @@protoc_insertion_point(field_get:CalcRequest.a)
  return a_;
}
inline void CalcRequest::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:CalcRequest.a)
}

// optional int32 b = 2;
inline void CalcRequest::clear_b() {
  b_ = 0;
}
inline ::google::protobuf::int32 CalcRequest::b() const {
  // @@protoc_insertion_point(field_get:CalcRequest.b)
  return b_;
}
inline void CalcRequest::set_b(::google::protobuf::int32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:CalcRequest.b)
}

inline const CalcRequest* CalcRequest::internal_default_instance() {
  return &CalcRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// CalcResponse

// optional int32 result = 1;
inline void CalcResponse::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 CalcResponse::result() const {
  // @@protoc_insertion_point(field_get:CalcResponse.result)
  return result_;
}
inline void CalcResponse::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:CalcResponse.result)
}

inline const CalcResponse* CalcResponse::internal_default_instance() {
  return &CalcResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_calculate_2eproto__INCLUDED
